AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.7

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false
